config/routes.rb
Rails.application.routes.draw do
  resources :pins

  mount Commontator::Engine => '/commontator'
 

  devise_for :users
  root "pins#index"
  get 'about' => 'pages#about'
  get 'tags/:tag', to: 'pins#index', as: :tag
 
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	validates :image, presence: true

	has_attached_file :document
	validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
	validates :document , presence: true
	acts_as_commontable
	is_impressionable
	acts_as_taggable
	# track user tag
	acts_as_taggable_on :locations

    end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :pins, dependent: :destroy
  
  validates :name, presence: true

  acts_as_commontator
  acts_as_tagger

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  impressionist actions: [:show], unique: [:session_hash]
  
  def index
    if params[:tag]

       @pins = Pin.order("created_at DESC").paginate(:page => params[:page], :per_page => 15).tagged_with(params[:tag])
    else
       @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
    end
  end

  def show
    commontator_thread_show(@pin)
    @pin = Pin.find(params[:id])
   impressionist(@pin)
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end
  
 def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end
  
  private
    
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id] )
      redirect_to pins_path, notice: "Not authorized to edit this Pin" if @pin.nil?
    end

    
    def pin_params
      params.require(:pin).permit(:description, :image, :document, :description_text, :paper, :tag_list, :duedate )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/commontator/comments/_votes.html.erb
<% # Clients of this partial must provide the following variables:
   # comment
   # user
%>

<% if comment.can_be_voted_on? %>
  <% can_vote = comment.can_be_voted_on_by?(user) %>
  <% vote = comment.get_vote_by(user) %>
  <% comment_voting = comment.thread.config.comment_voting.to_sym %>

  <% if comment_voting == :ld || comment_voting == :l %>
  <% vtype = (comment_voting == :ld) ? 'upvote' : 'like' %>
  <span id="comment_<%= comment.id %>_<%= vtype %>_span"
        class="comment_<%= vtype %>">
    <% if can_vote && (vote.blank? || !vote.vote_flag) %>
      <%= form_tag commontator.upvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/upvote.png",
              :onmouseover => "this.src='/assets/commontator/upvote_hover.png'",
              :onmouseout => "this.src='/assets/commontator/upvote.png'" %>
      <% end %>
    <% elsif can_vote %>
      <%= form_tag commontator.unvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/upvote_active.png",
              :onmouseover => "this.src='/assets/commontator/upvote.png'",
              :onmouseout => "this.src='/assets/commontator/upvote_active.png'"
        %>
      <% end %>
    <% else %>
      <%= image_tag "commontator/upvote_disabled.png" %>
    <% end %>
  </span>
  <% end %>

  <span id="comment_<%= comment.id %>_vote_count_span" class="comment_vote_count">
    <% config = comment.thread.config %>
    <%= config.vote_count_proc.call(comment.thread,
          comment.get_upvotes.size, comment.get_downvotes.size) %>
  </span>

  <% if comment_voting == :ld %>
  <span id="comment_<%= comment.id %>_downvote_span" class="comment_downvote">
    <% if can_vote && (vote.blank? || vote.vote_flag) %>
      <%= form_tag commontator.downvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/downvote.png",
              :onmouseover => "this.src='/assets/commontator/downvote_hover.png'",
              :onmouseout => "this.src='/assets/commontator/downvote.png'" %>
      <% end %>
    <% elsif can_vote %>
      <%= form_tag commontator.unvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/downvote_active.png",
              :onmouseover => "this.src='/assets/commontator/downvote.png'",
              :onmouseout => "this.src='/assets/commontator/downvote_active.png'"
        %>
      <% end %>
    <% else %>
      <%= image_tag "commontator/downvote_disabled.png" %>
    <% end %>
  </span>
  <% end %>
<% end %>

app/views/commontator/comments/delete.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render :partial => 'body', :locals => {:comment => @comment}) %>");

$("#comment_<%= @comment.id.to_s %>_updated_timestamp_span").html("<%= escape_javascript(
  @comment.updated_timestamp) %>");
                                                           
$("#comment_<%= @comment.id.to_s %>_actions_span").html("<%= escape_javascript(
  render :partial => 'actions',
         :locals => {:comment => @comment,
                     :user => @user}) %>");
         
$("#comment_<%= @comment.id %>_votes_span").html("<%= escape_javascript(
  render :partial => 'votes',
         :locals => {:comment => @comment,
                     :user => @user}) %>");

$("#comment_<%= @comment.id.to_s %>_div").hide();

<%= javascript_proc %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to '<span style="color: #e74c3c">P</span>aper<span style="color: #e67e22">S</span>tack'.html_safe, root_path, class: "navbar-brand" %>
    </div> 

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to 'Home', root_path %> </li>
        <li> <%= link_to 'About', about_path %> </li>
       
        <% if user_signed_in? %>
         
        <li><%= link_to  new_pin_path do %>
          
          <span class="glyphicon glyphicon-plus"></span>
            New <span style="color: #e74c3c">P</span>aper
          </button>
        <% end %>
        </li>
      
        <li><%= link_to edit_user_registration_path do %>
          <span class="glyphicon glyphicon-wrench"></span>
          Settings
          <% end %>
        </li>
        <li> <%= link_to 'Log out', destroy_user_session_path, method: :delete %> </li>
        <% else %>
         <li> <%= link_to 'Sign in', new_user_session_path %> </li>
        <% end %>

        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaperStack</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
		 
	<% end %>
	<%= yield %>
</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class='jumbotron center welcome'>
<h1>Welcome to <span style="color: #e74c3c">P</span>aper<span style="color: #e67e22">S</span>tack</h1>
<i>A place where you can publish your papers and get feedback on them</i>
  <p> <%= link_to "Learn more", about_path, class: "btn btn-primary btn-lg learn-more" %>
  </p>

</div>

<div class='jumbotron center'>
	<p> <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-danger' %> or <%= link_to "Log in", new_user_session_path, class: 'btn btn-default' %> </p>

</div>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-md-4">
	  	<div class= "jumbotron">
		  	  <img class="img-responsive" src="https://fbcdn-sphotos-d-a.akamaihd.net/hphotos-ak-xpa1/v/t1.0-9/10486005_10154294186385276_5690600788916377789_n.jpg?oh=c97a5443015093d0de757678d8896524&oe=54539229&__gda__=1413012287_54acc589f5f6fca49b64c124cd416b2f">
	  	</div>

  </div>

  <div class="col-md-8">
  	<div class="jumbotron">
  		<h2>The next step from good to GREAT paper</h2>
	  		<p>At <strong><span style="color: #e74c3c">P</span>aper<span style="color: #e67e22">S</span>tack</strong> you can showcase your essays, research papers, or any of your writings and get valuable feedback from the online community. </p>
  		<h3>Due date</h3>
	  		<p>When might you need feedback? You may be simply starting a paper and want to talk with another person about your plans. You may be halfway through a draft and observe that you are unsure about the direction you've chosen to take. You may ask why you got a lower grade than you expected on a paper. Basically, asking for feedback at any stage helps you break out of the confinement of writing.  By looking for criticism from others, you are taking positive, helpful steps to enhance your written work and develop as a writer.</p>
  		<p><span class="label label-primary">Publish</span> The first step for getting feedback is to post your paper online</p>
  		<p><span class="label label-success">Notes</span>Let others know what you are looking for. Whether you need help with your grammar, development of ideas, or just some quick feedback, it is always best to specify in your notes what you need from users</p>
  		<p><span class="label label-warning">Comments</span> Each essay posted will have a comment thread below it where people (including yourself) can discuss the different aspects of your essay. Users can up-vote or down-vote comments so that you can get the best feedback</p>
  		<p><span class="label label-danger">Editor</span>Building a community of student writers is tough. You need people who are willing to share their papers and review/edit the work of others. Look around for essays that might interest you-- help a brother out will you!</p>



  	</div>

 
  </div>
</div>

app/views/pages/home.html.erb
<div class='jumbotron center'>
<h1>Welcome to my app</h1>
<% if user_signed_in? %>
 # do something

<% else %>

<p> <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-danger' %> or <%= link_to "Log in", new_user_session_path, class: 'btn btn-default' %> </p>

<% end %>

</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
<div class="row">
  <div class="col-md-8">
    <div class="form-group has-error">
            <%= f.label :Title %><br>
            <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="form-group">
            <%= f.label :Paper %><br>
            <%= f.text_area :paper, :class => "tinymce", :rows => 30, :cols => 50 %>
    </div>
  </div>
</div>

  <div class="col-md-7">
      <div class="form-group has-error">
            <%= f.label :Notes %><br>
            <%= f.text_area :description_text, class: "form-control notes-height" %>
      </div>
      <div class="form-group">
        <%= f.label :document %> <span class="glyphicon glyphicon-file"></span>
        <%= f.file_field :document, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :image %> <span class="glyphicon glyphicon-picture"></span>
        <%= f.file_field :image, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :tag_list, "Tags (seperated by commas)" %>
        <%= f.text_field :tag_list %>
      </div>
      <div class="form-group">
        <%= f.label :duedate %>
        <%= f.datetime_select :duedate %>
      </div>
       <div class="form-group">
          <%= f.submit :class => 'btn btn-danger' %>
        </div>
    </div>
    

          
       </div>
    </div>

</div>
<% end %>

<%= tinymce %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

 <div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
        <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
         <p><%= pin.description %></p>
         <hr>
         <p>Tags: <%= raw pin.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
         <hr>
        <i>By: </i><strong><%= pin.user.name if pin.user %></strong> </br>
        <i>Posted: </i><%= pin.created_at.strftime("%d %b %y")  %>
         
          <% if current_user && pin.user == current_user %>
            <div class="actions">
              <%= link_to edit_pin_path(pin) do %>
                <span class="glyphicon glyphicon-edit"></span>
                Edit
              <% end %>
              <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
              <% end %>
            </div>

          <% end %>
          
      </div>
    </div>
   <% end %>
   <!--
   <div id="tag_cloud">
  <%= tag_cloud Pin.tag_counts, %w[s m l] do | tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div> !-->
</div>
<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="jumbotron jumbotron-about center">
			<h1><strong><span style="color: white">Publish</span></strong></h1>
		</div>
	</div>

	<div class="col-md-6">
		<div class="jumbotron center paper">
			<h1><strong><span style="color: #e74c3c">P</span>aper</strong></h1>
		</div>
	</div>

</div>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to pins_path do %>
<span class="glyphicon glyphicon-circle-arrow-left"></span>
<% end %>
<div class="container">
    <div class="row">
      <div class="col-md-offset-1 col-md-8">
        <div class="panel panel-default"> 
          <div class="panel-heading center">
            <div class="row">
              <div class="col-md-6">
                <%= image_tag @pin.image.url(:medium) %>
              </div>
              <div class="col-md-6">
                <div class="well">

                  <ul>
                    <li><i>Username </i> <strong><%= @pin.user.name if @pin.user %></strong>
                    <% if user_signed_in? %>
                        <li><i>Document </i> <%= link_to "My document", @pin.document.url, target: "_blank" %></li> 
                    <% end %>

                    <li><%= "#{@pin.impressionist_count} <strong>views</strong>".html_safe %></li>    
                    <li> Unique ip adress views <%= @pin.impressionist_count(:filter=>:ip_address) %></li>
                    <li>
                          Tags: <%= raw @pin.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
                    </li>
                    <li><strong>Due in:</strong></li>
                    <div id="due_date_timer" style="height: 44px;"></div>
                  

                      <% if @pin.user == current_user %>
                        <%= link_to edit_pin_path(@pin) do %>
                          <span class="glyphicon glyphicon-edit"></span>
                          Edit
                        <% end %>
                      <% end %>
                     
                    </ul>


                </div>
                

              </div> 

              

            </div>
           
          </div>

          <div class="panel-body scrollable-body">
              <%= @pin.paper.html_safe %>
          </div>
             
          
        </div>
      
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Notes</h3>
          </div>
          <div class="panel-body">
            <%= @pin.description_text %>
          </div>
        </div>
        <div class="jumbotron">
            <%= commontator_thread(@pin) %>
        </div>

      
      </div>
     
        
   </div>

</div>
 <script>
      var year = <%= @pin.duedate.year %>;
      var month = <%= @pin.duedate.month %>;
      var day = <%= @pin.duedate.day %>;

      var date = new Date(year, month, day);
      $("#due_date_timer").countdown({until: date});
  </script>